#! /bin/bash -e

source devstack.rc

# Mount iso files
mkdir -p $HOME_PATH/centos7
umount $HOME_PATH/centos7 || /bin/true
mount -o loop,rw -t iso9660 $OS_IMG $HOME_PATH/centos7

# Copy config files
./sync-config

# Start HTTP server
if which nginx; then
    cp config/netboot.conf /etc/nginx/conf.d
    systemctl restart nginx
else
    start_simple_http_server
fi

start_simple_http_server() {
    cd $HOME_PATH
    echo -n "Start HTTP server"
    kill $(ps -ef |grep SimpleHTTPServer | awk '{ print $2 }') 2>/dev/null || /bin/true
    for i in {1..3}; do
        echo -n "." && sleep 1
    done
    python -m SimpleHTTPServer 8800 >/tmp/simplehttp.log 2>&1 &
    echo
}

echo

cat >&1 <<EOF
Now config and http server are deployed, you can run "./boot.sh <name>" to init vm or
something else.

Example:
source devstack.env

EOF
