---
- name: Install Nova on Compute nodes
  hosts: compute
  user: root
  tasks:
    - name: Install Nova compute packages
      yum:
        name: "{{ item }}"
        state: "present"
      with_items:
        - openstack-nova-compute
        - openstack-neutron
        - openstack-neutron-openvswitch
    - name: Replace Nova config file
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      with_items:
        - src: nova/nova.conf.j2
          dest: /etc/nova/nova.conf

    - name: Enable and restart openstack-nova-compute service
      service: name=openstack-nova-compute state=restarted enabled=yes

  vars:
    management_ip: "{{ ansible_host }}"
    vncproxy_public_ip: 10.95.30.13
    vncproxy_management_ip: 192.168.100.10


- name: Add the compute node to the cell database(on controller)
  hosts: controller
  user: root
  tasks:
    - name: Descovery compute hosts
      command: "nova-manage cell_v2 discover_hosts"
      ignore_errors: true
