---
- name: Install Nova on Compute nodes
  hosts: compute
  user: root
  tasks:
    - name: Install Nova compute packages
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - openstack-nova-compute
        - openstack-neutron
        - openstack-neutron-openvswitch

    - name: Replace Nova config file
      template: src=nova/nova.conf.j2 dest=/etc/nova/nova.conf

    - name: Enable and restart openstack-nova-compute service
      service: name=openstack-nova-compute state=restarted enabled=yes
