---
- hosts: controller
  remote_user: root
  tasks:
  - name: Deploy NTP service
    template:
      src=/netboot/config/controller/etc/chrony.conf
      dest=/etc/chrony.conf
    notify:
      - restart chronyd

  - name: Install mariadb
    yum:
      name: mariadb
      state: latest
  - name: Install MariaDB
    yum:
      name: mariadb-server
      state: latest

  - name: ensure mariadb is running (and enable it at boot)
    service:
      name: mariadb
      state: started
      enabled: yes


  - name: Install python2-PyMySQL
    yum:
      name: python2-PyMySQL
      state: latest

  - name: Install rabbitmq-server
    yum:
      name: rabbitmq-server
      state: latest
    notify:
      - enable rabbitmq

  - name: ensure rabbitmq is running (and enable it at boot)
    service:
      name: rabbitmq-server
      state: started
      enabled: yes

  - name: Config MariaDB
    template:
      src=/netboot/config/controller/etc/my.cnf.d/openstack.cnf
      dest=/etc/my.cnf.d/openstack.cnf
    notify:
      - enable mariadb

  - name: Add rabbitmq openstack user
    command:
      rabbitmqctl add_user openstack cc
  - name: Set rabbitmq openstack permission
    command:
      rabbitmqctl set_permissions openstack ".*" ".*" ".*"

  handlers:
  - name: restart chronyd
    service:
      name: chronyd
      state: restarted
  - name: enable mariadb
    service:
      name: mariadb
      state: started
      enabled: yes
  - name: enable rabbitmq
    service:
      name: rabbitmq-server
      state: started
      enabled: yes
