- name: Install glance server
  hosts: controller
  user: root
  pre_tasks:
    - name: Create DB for glance service
      mysql_db:
        name: glance
    - name: Grant access to the DB for the glance service
      mysql_user:
        name: glance
        password: cc
        host: "{{ item }}"
        state: "present"
        priv: "glance.*:ALL"
      with_items:
        - "localhost"
        - "%"
  tasks:

    - name: Check glance user exists
      shell: source /root/adminrc && openstack user show -f json glance
      register: check_glance_user
      failed_when: check_glance_user.rc not in [0, 1]

    - name: Run init scripts
      script: scripts/glance-init.sh
      when: check_glance_user.rc == 0

    - name: Config glance
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      with_items:
        - src: glance/glance-api.conf.j2
          dest: /etc/glance/glance-api.conf
        - src: glance/glance-registry.conf.j2
          dest: /etc/glance/glance-registry.conf
      register: config_result

    - name: Perform a Glance DB sync
      command: "glance-manage db_sync"
      become: yes
      become_user: glance
      changed_when: false
      when: config_result.changed

    - name: Start service httpd, if not running
      service: name="{{ item }}" state=restarted enabled=yes
      with_items:
        - openstack-glance-api
        - openstack-glance-registry
      when: config_result.changed
