- name: Install Nova Api
  hosts: controller
  user: root
  pre_tasks:
    - name: Create DB for glance service
      mysql_db:
        name: "{{ item }}"
      with_items:
        - nova_api
        - nova
        - nova_cell0

    - name: Grant access to the DB for the Nova service
      mysql_user:
        name: nova
        password: cc
        host: "{{ item[0] }}"
        state: "present"
        priv: "{{ item[1] }}.*:ALL"
      loop: "{{ query('nested', [ '%', 'localhost' ], [ 'nova_api', 'nova', 'nova_cell0' ]) }}"

  tasks:
    - name: Check nova user
      shell: "source /root/adminrc && openstack user show nova"
      register: nova_user_check

    - name: Run nova init scripts
      script: scripts/nova-init.sh
      when: "{{ (nova_user_check.rc | int != 0) }}"

    - name: Install nova packages
      yum:
        name: "{{ nova_packages }}"
        state: "present"

    - name: Replace Nova config file
      template:
        src: nova.conf.j2
        dest: /etc/nova/nova.conf

    - name: Restart HTTP server
      service: name=httpd state=restarted enabled=yes

    - name: Perform a Glance DB sync
      command: "{{ item }}"
      become: yes
      become_user: nova
      with_items:
        - "nova-manage api_db sync"
        - "nova-manage cell_v2 map_cell0"
        - "nova-manage cell_v2 create_cell --name=cell1 --verbose"
        - "nova-manage db sync"

    - name: Start Nova service
      service: name="{{ item }}" state=restarted enabled=yes
      with_items:
        - openstack-nova-api
        - openstack-nova-consoleauth
        - openstack-nova-scheduler
        - openstack-nova-conductor
        - openstack-nova-novncproxy
  vars:
    nova_packages:
      - openstack-nova-api
      - openstack-nova-conductor
      - openstack-nova-console
      - openstack-nova-novncproxy
      - openstack-nova-scheduler
      - openstack-nova-placement-api
